version: "3"
services:

  zookeeper:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped
    volumes:
      - sma_zk_data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:2.8.0
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    restart: unless-stopped
    volumes:
      - sma_kafka_data:/bitnami/kafka

  postgres:
   image: postgres:latest
   container_name: postgres
   restart: unless-stopped
   environment:
     - POSTGRES_PASSWORD=pgpassword
     - POSTGRES_USER=toptweets
     - PGDATA=/var/lib/postgresql/data/pgdata
   volumes:
     - sma_pg_data:/var/lib/postgresql/data

  tw-stream-collector:
    image: ljufa/tw-stream-collector:${TAG}
    container_name: tw-stream-collector
    env_file:
      - .env
    depends_on:
      - kafka
    restart: unless-stopped

  tw-data:
    image: ljufa/tw-data:${TAG}
    container_name: tw-data
    depends_on:
      - kafka
    restart: unless-stopped

  backend:
   image: ljufa/backend:${TAG}
   container_name: backend
   env_file:
     - .env
   depends_on:
     - postgres
     - tw-data
   ports:
     - "8080:8080"
   restart: unless-stopped
   labels:
     - "traefik.http.routers.backend.rule=Host(`sma.dlj.freemyip.com`) && PathPrefix(`/api`)"
     - "traefik.enable=true"
     - "traefik.http.routers.backend.entrypoints=websecure"
     - "traefik.http.routers.backend.tls.certresolver=mydnschallenge"
     - "traefik.http.services.backend.loadbalancer.server.port=8080"

  web-ui:
   image: ljufa/web-ui:${TAG}
   container_name: web-ui
   depends_on:
     - backend
   restart: unless-stopped
#   ports:
#     - "80:8000"
   labels:
     - "traefik.enable=true"
     - "traefik.http.routers.web-ui.rule=Host(`sma.dlj.freemyip.com`)"
     - "traefik.http.routers.web-ui.entrypoints=websecure"
     - "traefik.http.routers.web-ui.tls.certresolver=mydnschallenge"
     - "traefik.http.services.web-ui.loadbalancer.server.port=80"

volumes:
  sma_kafka_data:
    driver: local
  sma_zk_data:
    driver: local
  sma_pg_data:
    driver: local

networks:
  default:
    external:
      name: proxy
